### ISSUE TITLE
Consider using a separate library for player interaction

### ISSUE THREAD

**Issue by PeterBurner** [DimitarNestorov/MusicBar#10]
I am currently looking for a library to interact with various media player apps on macOS. I came across a [LyricsX submodule](https://github.com/ddddxxx/MusicPlayer) and was pretty happy until I noticed that it does not work with VLC.
I did some digging and noticed that both MusicBar and LyricsX use the same private `MediaRemote` Framework from Apple.
According to your README you are currently working on a way to interact with VLC (and more). Would you consider using or at least contributing to the LyricsX submodule?
I think having a unified API for media players on macOS is really desirable and would also help other developers.
  
/cc  @ddddxxx

**Comment by DimitarNestorov** [comment]
What my plan is is to make a daemon which integrates VLC with the [Media Player API](https://developer.apple.com/documentation/mediaplayer) (which will integrate with MediaRemote under the hood). VLC allows interaction with it through Apple Script and I'm going to use that to attach it to the Media Player API. That way users will also gain the functionality to command VLC through Siri and other OS integrations.

**Comment by PeterBurner** [comment]
cool  
thats probably a much cleaner solution 👍  
I will keep an eye on your github account
