### ISSUE TITLE
Not working in macOS Ventura

### ISSUE THREAD

**Issue by mrleblanc101** [DimitarNestorov/MusicBar#19]
<img width="66" alt="Capture d’écran, le 2022-11-03 à 15 48 09" src="https://user-images.githubusercontent.com/17392251/199819861-bca9322a-f09b-480a-b91b-5a6e19d14c85.png">
<img width="217" alt="Capture d’écran, le 2022-11-03 à 15 48 36" src="https://user-images.githubusercontent.com/17392251/199819932-6f49007c-db45-4ad4-b96e-feb60a3bcb32.png">

**Comment by DimitarNestorov** [comment]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/8790386/199830326-fdf6e249-93ed-4093-b4bc-150826bca9be.png">

Works fine for me. I will need more information. What version of Ventura are you running? When does it stop responding (immediately or when using a specific player or when playing a specific song)? Have you tried deleting `~/Library/Preferences/com.dimitarnestorov.MusicBar.plist` and restarting the app (this will reset your preferences)? Have you tried restarting your computer?

**Comment by mrleblanc101** [comment]
Ventura Public version.
Crash on start, the menubar icon display a `?` and a few seconds later, macOS add an exclamation next to the icon saying it's not responding.

I'll try deleting the preference, resintalling too.

**Comment by mrleblanc101** [comment]
I deleted the preference file and the app using App Cleaner. Same problem. 

I forgot to mention, I'm on a 14" M1 Pro MacBook Pro so the app run in Rosetta.

**Comment by DimitarNestorov** [comment]
Reboot fixed it
