### ISSUE TITLE
AirPlay remote support

### ISSUE THREAD

**Issue by ale275** [DimitarNestorov/MusicBar#2]
Hi

it would be nice to support AirPlay device connected through Music app.

Here is an example of my HomePod playing a song using the mac as a remote

Ale

<img width="1026" alt="Screenshot 2020-05-01 13 09 50" src="https://user-images.githubusercontent.com/405331/80801549-17049200-8bad-11ea-9408-874869baeb88.png">

**Comment by DimitarNestorov** [comment]
Can you take a screenshot of the Now Playing widget in the Notification Center while you're playing music like that?

**Comment by ale275** [comment]
sure, here it is. It shows the right cover but no title and no playback control

<img width="331" alt="Screenshot 2020-05-01 13 17 41" src="https://user-images.githubusercontent.com/405331/80801968-39e37600-8bae-11ea-9ff2-0f029189cd34.png">

If then I press play, the playback stops and the playback bar goes to the right timing, if I press again playback starts again. No upgrade of the playback bar or button

**Comment by DimitarNestorov** [comment]
![image](https://user-images.githubusercontent.com/8790386/80802029-c85bf580-8bb6-11ea-841c-48e866326e4f.png)
I meant this.

**Comment by ale275** [comment]
same behaviour of the edited post above, so I think it's not your problem

<img width="328" alt="Screenshot 2020-05-01 13 20 58" src="https://user-images.githubusercontent.com/405331/80802104-a3fc1b00-8bae-11ea-9389-61ca9795c952.png">

**Comment by DimitarNestorov** [comment]
I don't have a HomePod but I installed AirServer to try out AirPlay. It seems to be working fine.

![image](https://user-images.githubusercontent.com/8790386/80802206-62bc3900-8bb7-11ea-9a2e-670dc757c220.png)

**Comment by ale275** [comment]
The difference here is that in this case you are streaming to the server, so iTunes is the player.
In my case HomePod is streaming by itself, iTunes is only a remote viewer and control (like the Remote iOS app) 

Probably there is nothing you can do about it

**Comment by DimitarNestorov** [comment]
I could be able to do something if I figure out a way to emulate a HomePod in this remote mode without buying one.

**Comment by ale275** [comment]
I tried with Xcode Simulator using apple tv but it doesn't allow to access music app. Can I help somehow?

**Comment by DimitarNestorov** [comment]
I tried the same, no luck either. Can you try a couple of the alternatives and tell me what your experience is with them. If they work fine maybe I can implement some kind of backup mode which relies on AppleScript.
https://apps.apple.com/bg/app/silicio-for-spotify-and-itunes/id933627574?mt=12
https://apps.apple.com/bg/app/whatson-now-playing/id1136082516?mt=12
https://apps.apple.com/bg/app/spotica-menu/id570549457?mt=12
https://apps.apple.com/bg/app/miniplay-for-spotify-itunes/id936243210?mt=12

**Comment by ale275** [comment]
None of those is working

https://support.apple.com/en-gb/guide/music/musb58944d8f/mac

here apple says about remote control and airplay, maybe the key is there. I will try to lookup a little bit in the developer documentation

**Comment by DimitarNestorov** [comment]
Last idea: iTunes. Here's an app that installs it on Catalina: https://github.com/cormiertyshawn895/Retroactive

**Comment by DimitarNestorov** [comment]
In Big Sur Music doesn't even show up in control center when remote controlling HomePods and/or Apple TVs. I think there's nothing I can do about it.
